#!/usr/bin/env ruby
require 'algoliasearch'
require 'awesome_print'
require 'json'
require 'nokogiri'

class Html2Json
  def initialize(*args)
    if args.length != 2
      puts 'Usage: ./parse_and_push apiKey source.html'
      exit 1
    end
    @api_key = args[0]
    @file = args[1]
  end

  def get_data(issue, name)
    input = issue.css("input[name=data-#{name}]")
    return nil unless input.length
    input.attr('value').text
  end

  def push_to_algolia(data)
      Algolia.init(api_key: @api_key,
                   application_id: 'O3F8QXYK6R')

      index = Algolia::Index.new('lepoint')
      settings = {
        attributesToIndex: %w(
          unordered(titles.cover),
          unordered(titles.france),
          unordered(titles.world),
          unordered(titles.society),
          unordered(titles.economy),
          unordered(titles.culture),
          unordered(titles.tendancies),
          unordered(titles.postillon),
          unordered(titles.bonus),
        ),
        customRanking: [
          'desc(numero)'
        ]
      }
      index.clear_index
      puts 'Updating settings'
      index.set_settings(settings)
      puts 'Pushing objects'
      ap data
      index.add_objects(data)
  end

  def get_records(doc)
    issues = doc.css('article')
    issues.map do |issue|
      {
        image: get_data(issue, 'image'),
        numero: get_data(issue, 'numero'),
        day: get_data(issue, 'day'),
        month: get_data(issue, 'month'),
        year: get_data(issue, 'year'),
        titles: {
          cover: get_data(issue, '1'),
          france: get_data(issue, '2'),
          world: get_data(issue, '3'),
          society: get_data(issue, '4'),
          economy: get_data(issue, '5'),
          culture: get_data(issue, '6'),
          tendancies: get_data(issue, '7'),
          postillon: get_data(issue, '8'),
          bonus: get_data(issue, '9')
        }
      }
    end
  end

  def run
    doc = Nokogiri::HTML(File.open(@file), nil, Encoding::UTF_8.to_s)
    puts 'Parsing HTML'
    records = get_records(doc)
    push_to_algolia(records)
  end
end
Html2Json.new(*ARGV).run
